# Builds the geleen world from 3D BAG (TU Delft, CC BY 4.0), BAG (Kadaster), AHN (PDOK, CC0)
# and OpenStreetMap (ODbL), all read once and written into fixtures beside the hand-made
# worlds. The sibling app's PostGIS database is read-only here, by PGOPTIONS as well as by
# rule; the AHN grid is the sibling's 10 m resample of PDOK's dtm_05m.
require "open3"

# Namespaced rather than left at the top of the file: a .rake file's bodies are blocks, so
# a bare constant or def in one lands on Object and is visible to every other task.
module GeleenImport
  DB = ENV.fetch("GELEEN_DB", "mijnstreek_drive_development")
  DEM = ENV.fetch("GELEEN_DEM", File.expand_path("~/Developer/mijnstreek/data/dem.raw"))
  ISLANDS = [ { name: "estate", cx: 186_330, cy: 332_234, radius: 50 },
              { name: "church", cx: 187_006, cy: 331_447, radius: 60 } ].freeze
  BOUNDS = [ 1150, -2350, 2100, -1350 ].freeze
  ORIGIN_Z = 60.0
  TILES = [ (2..4), (-5..-3) ].freeze
  FILES = { "worlds" => :world_yaml, "world_objects" => :objects_yaml, "terrain_tiles" => :tiles_yaml }.freeze

  def self.path(table) = Rails.root.join("test/fixtures", table, "geleen.yml")

  # ON_ERROR_STOP because psql exits 0 after a failed statement in a script: without it a
  # broken query comes back as empty output and a successful status, and the importer would
  # write a world with no buildings in it and say nothing.
  def self.query(file, vars)
    args = vars.flat_map { |k, v| [ "-v", "#{k}=#{v}" ] }
    out, err, status = Open3.capture3({ "PGOPTIONS" => "-c default_transaction_read_only=on" },
                                      "psql", "-d", DB, "-Atq", "-v", "ON_ERROR_STOP=1", *args,
                                      "-f", Rails.root.join("lib/import/geleen", file).to_s)
    raise "psql #{file}: #{err}" unless status.success?
    raise "psql #{file}: no rows -- is the window in the right place?" if out.strip.empty?

    JSON.parse(out)
  end
end

namespace :geleen do
  desc "Import the two islands into test/fixtures/{worlds,world_objects,terrain_tiles}/geleen.yml"
  task import: :environment do
    frame = Game::Terrain::Frame.mijnstreek
    bounds = GeleenImport::BOUNDS
    x0, y0 = frame.to_source(bounds[0], bounds[3])
    x1, y1 = frame.to_source(bounds[2], bounds[1])
    roads = GeleenImport.query("roads.sql", x0: x0, y0: y0, x1: x1, y1: y1)
                        .select { |r| Array(r["points"]).length >= 2 }
    game_roads = roads.map { |r| { "kind" => r["kind"], "width" => r["width"],
                                   "points" => r["points"].map { |x, y| frame.to_game(x, y).map { |v| v.round(2) } } } }

    dem = Game::Import::Dem.new(path: GeleenImport::DEM, origin_x: 165_500.0, origin_y: 423_500.0, step: 10.0, cols: 5050, rows: 11_850)
    tiles = Game::Import::Tiles.new(dem: dem, frame: frame, origin_z: GeleenImport::ORIGIN_Z)

    objects = GeleenImport::ISLANDS.flat_map do |island|
      vars = { cx: island[:cx], cy: island[:cy], radius: island[:radius] }
      window = GeleenImport.query("window.sql", vars)
      clusters = GeleenImport.query("rows.sql", vars)
      features = GeleenImport.query("features.sql", vars).to_h { |f| [ f["pand"], Game::Import::Classifier.category(f).to_s ] }
      Game::Import::Rows.new(window: window, clusters: clusters, frame: frame, roads: roads, categories: features).objects
        .map { |o| o.merge(name: "#{island[:name]}-#{o[:name]}") }
    end
    # One base per row: the mean ground under the corners of its dwellings' rectangle, or of its footprint.
    objects.each do |o|
      ring = o[:recipe]["footprint"]
      corners = [ [ ring.map(&:first).min, ring.map(&:last).min ], [ ring.map(&:first).max, ring.map(&:last).min ],
                  [ ring.map(&:first).max, ring.map(&:last).max ], [ ring.map(&:first).min, ring.map(&:last).max ] ]
      yaw = o[:yaw]
      o[:y] = (corners.sum { |lx, lz| tiles.ground(o[:x] + lx * Math.cos(yaw) - lz * Math.sin(yaw), o[:z] + lx * Math.sin(yaw) + lz * Math.cos(yaw)) } / 4.0).round(3)
    end

    txs, tzs = GeleenImport::TILES
    encoded = txs.flat_map { |tx| tzs.map { |tz| tiles.encode(tx, tz) } }
    spawns = [
      { "position" => [ 1330.0, (tiles.ground(1330.0, -2234.0) + 2.0).round(2), -2234.0 ], "yaw" => 0.82 },
      { "position" => [ 2006.0, (tiles.ground(2006.0, -1415.0) + 2.0).round(2), -1415.0 ], "yaw" => 3.14 }
    ]
    attribution = "Generated by bin/rails geleen:import on #{Date.today}. Buildings: 3D BAG (TU Delft, CC BY 4.0) over BAG (Kadaster). " \
                  "Terrain: AHN dtm_05m (PDOK, CC0) resampled to 10 m. Roads: OpenStreetMap contributors (ODbL). " \
                  "Islands: #{GeleenImport::ISLANDS.map { |i| "#{i[:name]} #{i[:radius]} m around RD (#{i[:cx]}, #{i[:cy]})" }.join('; ')}. Do not edit by hand."
    fixtures = Game::Import::Fixtures.new(slug: "geleen", name: "Geleen", frame: frame, origin_z: GeleenImport::ORIGIN_Z,
                                          bounds: bounds, spawns: spawns, roads: game_roads, objects: objects,
                                          tiles: encoded, attribution: attribution)
    GeleenImport::FILES.each do |table, message|
      yaml = fixtures.public_send(message)
      path = GeleenImport.path(table)
      FileUtils.mkdir_p(path.dirname)
      path.write(yaml)
      puts "wrote #{path.relative_path_from(Rails.root)} (#{yaml.bytesize} bytes)"
    end
    puts "#{objects.length} buildings, #{encoded.length} tiles, #{game_roads.length} roads"
  end

  # NOT db:seed. That loads every fixture table, which replaces the hand-made world rows
  # with fresh ones -- new ids, and every match ever played on them orphaned. This touches
  # geleen and nothing else: the world by its slug, its buildings by name, its tiles by
  # their coordinates. Stale geleen rows the fixtures no longer name are removed, because a
  # row left behind keeps serving a building the import stopped producing.
  desc "Upsert only the geleen rows from the generated fixtures into the connected database"
  task seed: :environment do
    missing = GeleenImport::FILES.keys.reject { |table| GeleenImport.path(table).exist? }
    abort "no fixtures to seed: #{missing.join(', ')} -- run bin/rails geleen:import first" if missing.any?

    # unsafe_load because the tiles carry !!binary, which safe_load will not build. Named
    # one by one rather than zipped off FILES, so reordering that hash cannot quietly load
    # the tiles as the world.
    worlds = YAML.unsafe_load_file(GeleenImport.path("worlds"))
    objects = YAML.unsafe_load_file(GeleenImport.path("world_objects"))
    tiles = YAML.unsafe_load_file(GeleenImport.path("terrain_tiles"))

    row = worlds.fetch("geleen")
    world = World.find_or_initialize_by(slug: row.fetch("slug"))
    world.update!(row.except("slug"))

    names = objects.each_value.map do |object|
      raise "#{object['name']} belongs to #{object['world']}, not geleen" unless object.fetch("world") == world.slug

      record = world.world_objects.find_or_initialize_by(name: object.fetch("name"))
      record.update!(object.except("world", "name"))
      record.name
    end
    coordinates = tiles.each_value.map do |tile|
      raise "tile #{tile['tx']},#{tile['tz']} belongs to #{tile['world']}, not geleen" unless tile.fetch("world") == world.slug

      record = world.terrain_tiles.find_or_initialize_by(tx: tile.fetch("tx"), tz: tile.fetch("tz"))
      record.update!(tile.except("world", "tx", "tz"))
      [ record.tx, record.tz ]
    end

    stale_objects = world.world_objects.where.not(name: names).destroy_all.length
    # Selected without the blob: nine heightfields is half a megabyte to load in order to
    # find out that none of them is stale.
    stale_tiles = world.terrain_tiles.select(:id, :tx, :tz).reject { |t| coordinates.include?([ t.tx, t.tz ]) }.each(&:destroy).length
    puts "geleen: #{names.length} objects, #{coordinates.length} tiles" \
         "#{" (removed #{stale_objects} stale objects, #{stale_tiles} stale tiles)" if stale_objects.positive? || stale_tiles.positive?}"
  end
end
